# Python para Inteligência Artificial
---

**Professor: Dr. Daniel Neri Cardoso**

## Módulo 3 — NumPy

### Lista de exercícios


**Aluna: Angelina de Meiras Ottoni**

# =========================================
# Exercise 1 — Criação de Arrays
# =========================================

In [2]:
%pip install numpy

  Using cached numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
# Um vetor (array 1D) contendo os números pares de 2 a 10
even_numbers = np.array([2, 4, 6, 8, 10])

print(even_numbers)

[ 2  4  6  8 10]


In [6]:
# Uma matriz (array 2D) de tamanho 3 × 3 preenchida apenas com zeros (use np.zeros)
zero_matrix = np.zeros((3, 3))

print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# =========================================
# Exercise 2 — Inspeção de Dimensões
# =========================================

In [7]:
matrix = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
)

In [10]:
# O formato da matriz (quantas linhas e colunas)
print(f"Shape: {matrix.shape}")

# O número total de elementos na matriz
print(f"Total elements: {matrix.size}")

# O número de dimensões (eixos) da matriz
print(f"Number of dimensions: {matrix.ndim}")

Shape: (2, 4)
Total elements: 8
Number of dimensions: 2


# =========================================
# Exercise 3 — Matemática Vetorizada
# =========================================

In [15]:
values = np.array([
    50, 100, 150, 200
])

print(values)

# Aplica aumento de 10% a todos os valores simultaneamente (multiplique por 1.1)
values = values * 1.1

#Subtraia 5 de todos os valores obtidos
values = values - 5

# Imprima o array resultante
print(values)

[ 50 100 150 200]
[ 50. 105. 160. 215.]


# =========================================
# Exercise 4 — Indexação e Slicing
# =========================================

In [ ]:
data = np . array ([[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]])

In [17]:
# Sleciona o número 60
print(data[1, 2])

60


In [18]:
# Seleciona a primeira linha
print(data[0])

[10 20 30]


# =========================================
# Exercise 5 — Produto Matricial
# =========================================

In [19]:
A = np.array([
    [1, 2],
    [3, 4]
])

In [20]:
B = np.array([
    [5 ,6],
    [7, 8]
])

In [22]:
result = A @ B
print(result)

[[19 22]
 [43 50]]


**Conceito importante** 
- \* → multiplicação elemento a elemento   
- @ → multiplicação matricial real

# =========================================
# Exercise 6 — Estatísticas
# =========================================

In [23]:
grades = np.array([7.5, 8.0, 9.5, 6.0, 10.0])

print("Max:", np.max(grades))
print("Min:", np.min(grades))
print("Mean:", np.mean(grades))

Max: 10.0
Min: 6.0
Mean: 8.2


# =========================================
# Exercise 7 — A função `argmax`
# =========================================

In [25]:
probs = np.array([0.15, 0.75, 0.10])

predicted_class = np.argmax(probs)

print(f"Predicted class index: {predicted_class}")

Predicted class index: 1


# =========================================
# Exercise 8 — Reshape e Flatten
# =========================================

In [29]:
vector = np.arange(12)

print(vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
matrix = vector.reshape(3, 4)

print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
flattened = matrix.flatten()

print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# =========================================
# Exercise 9 — Filtros Lógicos
# =========================================

In [31]:
ages = np.array([12, 18, 25, 15, 30, 42, 17])

adult_ages = ages[ages >= 18]

print(adult_ages)

[18 25 30 42]


# =========================================
# Exercise 10 — Limpeza Condicional
# =========================================

In [32]:
temp = np.array([30, -10, 25, 28, -5])

clean_temp = np.where(temp < 0, 0, temp)

print(clean_temp)

[30  0 25 28  0]
